server:
  port: 8081
spring.cloud.stream:
  function:
    definition: orderSupplier;eventConsumer
  bindings:
    orderSupplier-out-0:
      destination: order-created
    eventConsumer-in-0:
      destination: order-updated
---
spring:
  jpa:
    defer-datasource-initialization: true
